 InternalError("Throwable(Object(java/lang/NullPointerException)
  backtrace=java/lang/StackTraceElement[11]
  detailMessage=Object(null)
  cause=Object(class java/lang/NullPointerException)
  stackTrace=java/lang/StackTraceElement[0]
  depth=int(11)
  suppressedExceptions=Object(class java/util/Collections$EmptyList)
  extendedMessageState=int(1)
  extendedMessage=Object(null)
):
