InternalError("Throwable(Object(Some(Object(RwLock { data: Object(java/lang/NullPointerException)
  backtrace=java/lang/StackTraceElement[15]
  detailMessage=String(\"array cannot be null\")
  cause=Object(class java/lang/NullPointerException)
  stackTrace=java/lang/StackTraceElement[0]
  depth=int(15)
  suppressedExceptions=Object(class java/util/Collections$EmptyList)
  extendedMessageState=int(1)
  extendedMessage=Object(null)
 })))):
stdout: --- Test Record in Inner Class ---

stderr: ")
